#!/bin/bash

# Quick Deployment Guide
# This file shows the simplest ways to get your portfolio online

echo "🚀 Portfolio Deployment Options"
echo "================================"
echo ""
echo "Option 1: GITHUB PAGES (Easiest - 2 minutes)"
echo "-------------------------------------------"
echo "1. Go to: https://github.com/gsaiganesh283/Portfolio_V.1"
echo "2. Click Settings → Pages"
echo "3. Select 'main' branch → Save"
echo "4. Wait 1-2 minutes"
echo "5. Your site: https://gsaiganesh283.github.io/Portfolio_V.1/"
echo ""
echo ""
echo "Option 2: NETLIFY (Best Features - 3 minutes)"
echo "--------------------------------------------"
echo "1. Go to: https://netlify.com"
echo "2. Click 'Sign up' → Connect GitHub"
echo "3. Select 'Portfolio_V.1' → Deploy"
echo "4. Your site: https://[name].netlify.app"
echo ""
echo ""
echo "Option 3: VERCEL (Fastest - 3 minutes)"
echo "-------------------------------------"
echo "1. Go to: https://vercel.com"
echo "2. Click 'Sign up' → Connect GitHub"
echo "3. Import 'Portfolio_V.1' → Deploy"
echo "4. Your site: https://portfolio-v1.vercel.app"
echo ""
echo ""
echo "📱 After Deployment:"
echo "==================="
echo "• Public Portfolio: https://your-deployed-url/"
echo "• Admin Panel: https://your-deployed-url/admin.html"
echo "  Login: admin / admin123"
echo ""
echo "🔄 Make Updates:"
echo "==============="
echo "1. Edit files locally"
echo "2. git add ."
echo "3. git commit -m 'Update portfolio'"
echo "4. git push origin main"
echo "5. Site updates automatically!"
echo ""
echo "For detailed guide, see HOSTING.md"
